package org.modcal;

import java.util.HashMap;


/**
 * A mapping of Strings (the names of the parameters) to their data that is
 * to be inserted into an otherwise constant {@link ModelInput}.
 * A new one of these is generated by the {@link Sampler} for each iteration of the {@Model}.
 * 
 * @author Victor Mataré
 *
 */
public abstract class ParameterSample<DataT extends CharSequence> extends HashMap<String, DataT> {

	private static final long serialVersionUID = -1125256651282162310L;
	
}
